server:
  port: 8087

spring:
  application:
    name: c360-service
  datasource:
    url: jdbc:postgresql://localhost:5432/c360_db
    username: crm_admin
    password: crm_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
